name: CodSpeed Benchmarks

on:
  push:
    branches:
      - "main" # or "master"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks-rust:
    name: Run codspeed - Rust benches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed
      - name: Download benchmark SVG fixtures
        run: sh crates/oxvg_optimiser/benches/download_svgs.sh
      - name: Build the benchmark target(s)
        run: cargo codspeed build
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: cargo codspeed run

  benchmarks-napi:
    name: Run codspeed - napi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm i
      - name: Setup rust toolchain, cache
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
          cache-target: release
      - name: Build napi
        run: pnpm --filter napi run build
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: cd node-bench && pnpm i && pnpm run bench